language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi

script: 
	mkdir build && cd build && cmake .. && make
