version: 0.6.{build}

shallow_clone: true

platform:
    - x64
    - x86

configuration:
    - Visual Studio 10.0
    - Visual Studio 12.0
    - Visual Studio 14.0

before_build:
    - call "%ProgramFiles(x86)%\Microsoft %configuration%\VC\vcvarsall.bat" %platform%
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" ..

build_script: nmake