shallow_clone: true

environment:
    matrix:
    - PLATFORM: x86
    - PLATFORM: amd64

before_build:
    - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" ..
    - nmake
